apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-backup
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: {storageClassName}
  volumeMode: Filesystem
---

apiVersion: redis.kun/v1alpha1
kind: RedisClusterBackup
metadata:
  name: example-redisclusterbackup
  annotations:
    redis.kun/scope: cluster-scoped
spec:
  image: uhub.service.ucloud.cn/operator/redis-tools:5.0.4
  # on same namespace
  redisClusterName: test
  local:
    mountPath: /back
    persistentVolumeClaim:
      claimName: test-backup
