apiVersion: redis.kun/v1alpha1
kind: DistributedRedisCluster
metadata:
  annotations:
    # if your operator run as cluster-scoped, add this annotations
    redis.kun/scope: cluster-scoped
  name: example-restore
spec:
  init:
    backupSource:
      name: example-redisclusterbackup
      namespace: default
